version: "3"
services:
  node_crawler:
    build: ./
    image: node_crawler
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - .:/var/www
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis:latest
    ports:
      - 63790:6379